// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using System.Collections.Generic;
using MahApps.Metro.Gallery.Pages;
using MahApps.Metro.IconPacks;

namespace MahApps.Metro.Gallery.Core
{
    /// <summary>
    /// Every page there is, in the order the navigation shows them. Add a page here and it turns up
    /// in the navigation and in the search, both of which read nothing else.
    /// </summary>
    public static class GalleryPages
    {
        public static IReadOnlyList<GalleryPage> All { get; } = new[]
                                                               {
                                                                   new GalleryPage("AutoSuggestBox",
                                                                                   "Controls",
                                                                                   typeof(AutoSuggestBoxPage),
                                                                                   PackIconMaterialKind.TextSearch,
                                                                                   keywords: "search suggest complete",
                                                                                   control: "Controls/AutoSuggestBox/AutoSuggestBox.cs"),
                                                                   new GalleryPage("Badged",
                                                                                   "Controls",
                                                                                   typeof(BadgedPage),
                                                                                   PackIconMaterialKind.Numeric1CircleOutline,
                                                                                   keywords: "badge count notification",
                                                                                   control: "Controls/Badged.cs"),
                                                                   new GalleryPage("ColorPicker",
                                                                                   "Controls",
                                                                                   typeof(ColorPickerPage),
                                                                                   PackIconMaterialKind.Palette,
                                                                                   keywords: "colour canvas palette",
                                                                                   control: "Controls/ColorPicker/ColorPicker.cs"),
                                                                   new GalleryPage("DateTimePicker",
                                                                                   "Controls",
                                                                                   typeof(DateTimePickerPage),
                                                                                   PackIconMaterialKind.CalendarClock,
                                                                                   keywords: "date time clock calendar",
                                                                                   control: "Controls/TimePicker/DateTimePicker.cs"),
                                                                   new GalleryPage("DropDownButton",
                                                                                   "Controls",
                                                                                   typeof(DropDownButtonPage),
                                                                                   PackIconMaterialKind.MenuDown,
                                                                                   keywords: "menu split button",
                                                                                   control: "Controls/DropDownButton.cs"),
                                                                   new GalleryPage("FlipView",
                                                                                   "Controls",
                                                                                   typeof(FlipViewPage),
                                                                                   PackIconMaterialKind.ViewCarouselOutline,
                                                                                   keywords: "carousel banner pages",
                                                                                   control: "Controls/FlipView.cs"),
                                                                   new GalleryPage("Flyout",
                                                                                   "Controls",
                                                                                   typeof(FlyoutPage),
                                                                                   PackIconMaterialKind.PageLayoutSidebarRight,
                                                                                   // the page over there is called flyouts
                                                                                   "controls/flyouts",
                                                                                   "panel slide settings",
                                                                                   "Controls/Flyout.cs"),
                                                                   new GalleryPage("FontIcon",
                                                                                   "Controls",
                                                                                   typeof(FontIconPage),
                                                                                   PackIconMaterialKind.FormatFont,
                                                                                   keywords: "glyph icon font segoe",
                                                                                   control: "Controls/Icons/FontIcon.cs"),
                                                                   new GalleryPage("HamburgerMenu",
                                                                                   "Controls",
                                                                                   typeof(HamburgerMenuPage),
                                                                                   PackIconMaterialKind.Menu,
                                                                                   keywords: "navigation pane drawer",
                                                                                   control: "Controls/HamburgerMenu/HamburgerMenu.cs"),
                                                                   new GalleryPage("HotKeyBox",
                                                                                   "Controls",
                                                                                   typeof(HotKeyBoxPage),
                                                                                   PackIconMaterialKind.KeyboardOutline,
                                                                                   keywords: "shortcut keys hotkey",
                                                                                   control: "Controls/HotKeyBox.cs"),
                                                                   new GalleryPage("MetroHeader",
                                                                                   "Controls",
                                                                                   typeof(MetroHeaderPage),
                                                                                   PackIconMaterialKind.FormatHeader3,
                                                                                   keywords: "label caption form",
                                                                                   control: "Controls/MetroHeader.cs"),
                                                                   new GalleryPage("MetroProgressBar",
                                                                                   "Controls",
                                                                                   typeof(MetroProgressBarPage),
                                                                                   PackIconMaterialKind.ProgressHelper,
                                                                                   keywords: "progress bar indeterminate waiting",
                                                                                   control: "Controls/MetroProgressBar.cs"),
                                                                   new GalleryPage("MetroTabControl",
                                                                                   "Controls",
                                                                                   typeof(MetroTabControlPage),
                                                                                   PackIconMaterialKind.TabUnselected,
                                                                                   keywords: "tabs animated underline",
                                                                                   control: "Controls/MetroTabControl.cs"),
                                                                   new GalleryPage("MetroTabItem",
                                                                                   "Controls",
                                                                                   typeof(MetroTabItemPage),
                                                                                   PackIconMaterialKind.TabPlus,
                                                                                   keywords: "tab close button",
                                                                                   control: "Controls/MetroTabItem.cs"),
                                                                   new GalleryPage("MetroThumbContentControl",
                                                                                   "Controls",
                                                                                   typeof(MetroThumbContentControlPage),
                                                                                   PackIconMaterialKind.DragVariant,
                                                                                   keywords: "drag move thumb",
                                                                                   control: "Controls/MetroThumbContentControl.cs"),
                                                                   new GalleryPage("MetroWindow",
                                                                                   "Controls",
                                                                                   typeof(MetroWindowPage),
                                                                                   PackIconMaterialKind.WindowMaximize,
                                                                                   keywords: "window title bar chrome commands",
                                                                                   control: "Controls/MetroWindow.cs"),
                                                                   new GalleryPage("MultiFrameImage",
                                                                                   "Controls",
                                                                                   typeof(MultiFrameImagePage),
                                                                                   PackIconMaterialKind.ImageMultipleOutline,
                                                                                   keywords: "icon image frames",
                                                                                   control: "Controls/MultiFrameImage.cs"),
                                                                   new GalleryPage("NumericUpDown",
                                                                                   "Controls",
                                                                                   typeof(NumericUpDownPage),
                                                                                   PackIconMaterialKind.Counter,
                                                                                   keywords: "number spinner value",
                                                                                   control: "Controls/NumericUpDown.cs"),
                                                                   new GalleryPage("ProgressRing",
                                                                                   "Controls",
                                                                                   typeof(ProgressRingPage),
                                                                                   PackIconMaterialKind.Loading,
                                                                                   keywords: "spinner busy waiting",
                                                                                   control: "Controls/ProgressRing.cs"),
                                                                   new GalleryPage("RangeSlider",
                                                                                   "Controls",
                                                                                   typeof(RangeSliderPage),
                                                                                   PackIconMaterialKind.ArrowExpandHorizontal,
                                                                                   keywords: "range from to slider",
                                                                                   control: "Controls/RangeSlider.cs"),
                                                                   new GalleryPage("SplitButton",
                                                                                   "Controls",
                                                                                   typeof(SplitButtonPage),
                                                                                   PackIconMaterialKind.CallSplit,
                                                                                   keywords: "split button selection",
                                                                                   control: "Controls/SplitButton.cs"),
                                                                   new GalleryPage("SplitView",
                                                                                   "Controls",
                                                                                   typeof(SplitViewPage),
                                                                                   PackIconMaterialKind.ViewSplitVertical,
                                                                                   keywords: "pane drawer navigation",
                                                                                   control: "Controls/SplitView/SplitView.cs"),
                                                                   new GalleryPage("Tile",
                                                                                   "Controls",
                                                                                   typeof(TilePage),
                                                                                   PackIconMaterialKind.ViewDashboardOutline,
                                                                                   keywords: "tile start screen button count",
                                                                                   control: "Controls/Tile.cs"),
                                                                   new GalleryPage("TimePicker",
                                                                                   "Controls",
                                                                                   typeof(TimePickerPage),
                                                                                   PackIconMaterialKind.ClockOutline,
                                                                                   keywords: "time clock hours minutes",
                                                                                   control: "Controls/TimePicker/TimePicker.cs"),
                                                                   new GalleryPage("ToggleSwitch",
                                                                                   "Controls",
                                                                                   typeof(ToggleSwitchPage),
                                                                                   PackIconMaterialKind.ToggleSwitch,
                                                                                   keywords: "switch on off toggle",
                                                                                   control: "Controls/ToggleSwitch.cs"),
                                                                   new GalleryPage("TransitioningContentControl",
                                                                                   "Controls",
                                                                                   typeof(TransitioningContentControlPage),
                                                                                   PackIconMaterialKind.Transition,
                                                                                   keywords: "transition animation slide content",
                                                                                   control: "Controls/TransitioningContentControl.cs"),
                                                                   new GalleryPage("WindowButtonCommands",
                                                                                   "Controls",
                                                                                   typeof(WindowButtonCommandsPage),
                                                                                   PackIconMaterialKind.WindowClose,
                                                                                   keywords: "minimize maximize close title bar",
                                                                                   control: "Controls/WindowButtonCommands.cs"),
                                                                   new GalleryPage("WindowCommands",
                                                                                   "Controls",
                                                                                   typeof(WindowCommandsPage),
                                                                                   PackIconMaterialKind.DockTop,
                                                                                   keywords: "title bar commands toolbar",
                                                                                   control: "Controls/WindowCommands.cs"),
                                                                   new GalleryPage("Button",
                                                                                   "Styles",
                                                                                   typeof(ButtonPage),
                                                                                   PackIconMaterialKind.GestureTapButton,
                                                                                   // the page over there is called buttons, not button
                                                                                   "styles/buttons",
                                                                                   "square circle flat accent",
                                                                                   // a style rather than a control, so the styles are where to look
                                                                                   "Styles/Controls.Buttons.xaml")
                                                               };
    }
}
