namespace MahApps.Metro.Controls
{
    using System.ComponentModel;

    /// ******************************************
    /// This code is auto generated. Do not amend.
    /// ******************************************

    /// <summary>
    /// List of available icons for use with <see cref="PackIconFontAwesome" />.
    /// </summary>
    /// <remarks>
    /// All icons sourced from FontAwesome Icons Font v4.6.3 - <see><cref>http://fontawesome.io</cref></see> - 
    /// <see><cref>https://github.com/FortAwesome/Font-Awesome</cref></see>.
    /// </remarks>
    public enum PackIconFontAwesomeKind
    {
        [Description("500px")] _500px,
        [Description("adjust")] Adjust,
        [Description("App.net")] Adn,
        [Description("align-center")] AlignCenter,
        [Description("align-justify")] AlignJustify,
        [Description("align-left")] AlignLeft,
        [Description("align-right")] AlignRight,
        [Description("Amazon")] Amazon,
        [Description("ambulance")] Ambulance,
        [Description("American Sign Language Interpreting (AslInterpreting)")] AmericanSignLanguageInterpreting,
        [Description("Anchor")] Anchor,
        [Description("Android")] Android,
        [Description("AngelList")] Angellist,
        [Description("Angle Double Down")] AngleDoubleDown,
        [Description("Angle Double Left")] AngleDoubleLeft,
        [Description("Angle Double Right")] AngleDoubleRight,
        [Description("Angle Double Up")] AngleDoubleUp,
        [Description("angle-down")] AngleDown,
        [Description("angle-left")] AngleLeft,
        [Description("angle-right")] AngleRight,
        [Description("angle-up")] AngleUp,
        [Description("Apple")] Apple,
        [Description("Archive")] Archive,
        [Description("Area Chart")] AreaChart,
        [Description("Arrow Circle Down")] ArrowCircleDown,
        [Description("Arrow Circle Left")] ArrowCircleLeft,
        [Description("Arrow Circle Outlined Down")] ArrowCircleOutlineDown,
        [Description("Arrow Circle Outlined Left")] ArrowCircleOutlineLeft,
        [Description("Arrow Circle Outlined Right")] ArrowCircleOutlineRight,
        [Description("Arrow Circle Outlined Up")] ArrowCircleOutlineUp,
        [Description("Arrow Circle Right")] ArrowCircleRight,
        [Description("Arrow Circle Up")] ArrowCircleUp,
        [Description("arrow-down")] ArrowDown,
        [Description("arrow-left")] ArrowLeft,
        [Description("arrow-right")] ArrowRight,
        [Description("Arrows")] Arrows,
        [Description("Arrows Alt")] ArrowsAlt,
        [Description("Arrows Horizontal")] ArrowsH,
        [Description("Arrows Vertical")] ArrowsV,
        [Description("arrow-up")] ArrowUp,
        [Description("Assistive Listening Systems")] AssistiveListeningSystems,
        [Description("asterisk")] Asterisk,
        [Description("At")] At,
        [Description("Audio Description")] AudioDescription,
        [Description("backward")] Backward,
        [Description("Balance Scale")] BalanceScale,
        [Description("ban")] Ban,
        [Description("Bar Chart (BarChartOutline)")] BarChart,
        [Description("barcode")] Barcode,
        [Description("Bars (Navicon, Reorder)")] Bars,
        [Description("Battery Empty (Battery0)")] BatteryEmpty,
        [Description("Battery Full (Battery4)")] BatteryFull,
        [Description("Battery 1/2 Full (Battery2)")] BatteryHalf,
        [Description("Battery 1/4 Full (Battery1)")] BatteryQuarter,
        [Description("Battery 3/4 Full (Battery3)")] BatteryThreeQuarters,
        [Description("Bed (Hotel)")] Bed,
        [Description("beer")] Beer,
        [Description("Behance")] Behance,
        [Description("Behance Square")] BehanceSquare,
        [Description("bell")] Bell,
        [Description("Bell Outlined")] BellOutline,
        [Description("Bell Slash")] BellSlash,
        [Description("Bell Slash Outlined")] BellSlashOutline,
        [Description("Bicycle")] Bicycle,
        [Description("Binoculars")] Binoculars,
        [Description("Birthday Cake")] BirthdayCake,
        [Description("Bitbucket")] Bitbucket,
        [Description("Bitbucket Square")] BitbucketSquare,
        [Description("Font Awesome Black Tie")] BlackTie,
        [Description("Blind")] Blind,
        [Description("Bluetooth")] Bluetooth,
        [Description("Bluetooth")] BluetoothB,
        [Description("bold")] Bold,
        [Description("Lightning Bolt (Flash)")] Bolt,
        [Description("Bomb")] Bomb,
        [Description("book")] Book,
        [Description("bookmark")] Bookmark,
        [Description("Bookmark Outlined")] BookmarkOutline,
        [Description("Braille")] Braille,
        [Description("Briefcase")] Briefcase,
        [Description("Bitcoin (BTC) (Bitcoin)")] Btc,
        [Description("Bug")] Bug,
        [Description("Building")] Building,
        [Description("Building Outlined")] BuildingOutline,
        [Description("bullhorn")] Bullhorn,
        [Description("Bullseye")] Bullseye,
        [Description("Bus")] Bus,
        [Description("BuySellAds")] Buysellads,
        [Description("Calculator")] Calculator,
        [Description("calendar")] Calendar,
        [Description("Calendar Check Outlined")] CalendarCheckOutline,
        [Description("Calendar Minus Outlined")] CalendarMinusOutline,
        [Description("calendar-o")] CalendarOutline,
        [Description("Calendar Plus Outlined")] CalendarPlusOutline,
        [Description("Calendar Times Outlined")] CalendarTimesOutline,
        [Description("camera")] Camera,
        [Description("camera-retro")] CameraRetro,
        [Description("Car (Automobile)")] Car,
        [Description("Caret Down")] CaretDown,
        [Description("Caret Left")] CaretLeft,
        [Description("Caret Right")] CaretRight,
        [Description("Caret Square Outlined Down (ToggleDown)")] CaretSquareOutlineDown,
        [Description("Caret Square Outlined Left (ToggleLeft)")] CaretSquareOutlineLeft,
        [Description("Caret Square Outlined Right (ToggleRight)")] CaretSquareOutlineRight,
        [Description("Caret Square Outlined Up (ToggleUp)")] CaretSquareOutlineUp,
        [Description("Caret Up")] CaretUp,
        [Description("Shopping Cart Arrow Down")] CartArrowDown,
        [Description("Add to Shopping Cart")] CartPlus,
        [Description("Closed Captions")] Cc,
        [Description("American Express Credit Card")] CcAmex,
        [Description("Diner's Club Credit Card")] CcDinersClub,
        [Description("Discover Credit Card")] CcDiscover,
        [Description("JCB Credit Card")] CcJcb,
        [Description("MasterCard Credit Card")] CcMastercard,
        [Description("Paypal Credit Card")] CcPaypal,
        [Description("Stripe Credit Card")] CcStripe,
        [Description("Visa Credit Card")] CcVisa,
        [Description("certificate")] Certificate,
        [Description("Chain Broken (Unlink)")] ChainBroken,
        [Description("Check")] Check,
        [Description("Check Circle")] CheckCircle,
        [Description("Check Circle Outlined")] CheckCircleOutline,
        [Description("Check Square")] CheckSquare,
        [Description("Check Square Outlined")] CheckSquareOutline,
        [Description("Chevron Circle Down")] ChevronCircleDown,
        [Description("Chevron Circle Left")] ChevronCircleLeft,
        [Description("Chevron Circle Right")] ChevronCircleRight,
        [Description("Chevron Circle Up")] ChevronCircleUp,
        [Description("chevron-down")] ChevronDown,
        [Description("chevron-left")] ChevronLeft,
        [Description("chevron-right")] ChevronRight,
        [Description("chevron-up")] ChevronUp,
        [Description("Child")] Child,
        [Description("Chrome")] Chrome,
        [Description("Circle")] Circle,
        [Description("Circle Outlined")] CircleOutline,
        [Description("Circle Outlined Notched")] CircleOutlineNotch,
        [Description("Circle Outlined Thin")] CircleThin,
        [Description("Clipboard (Paste)")] Clipboard,
        [Description("Clock Outlined")] ClockOutline,
        [Description("Clone")] Clone,
        [Description("Cloud")] Cloud,
        [Description("Cloud Download")] CloudDownload,
        [Description("Cloud Upload")] CloudUpload,
        [Description("Code")] Code,
        [Description("code-fork")] CodeFork,
        [Description("Codepen")] Codepen,
        [Description("Codie Pie")] Codiepie,
        [Description("Coffee")] Coffee,
        [Description("cog (Gear)")] Cog,
        [Description("cogs (Gears)")] Cogs,
        [Description("Columns")] Columns,
        [Description("comment")] Comment,
        [Description("Commenting")] Commenting,
        [Description("Commenting Outlined")] CommentingOutline,
        [Description("comment-o")] CommentOutline,
        [Description("comments")] Comments,
        [Description("comments-o")] CommentsOutline,
        [Description("Compass")] Compass,
        [Description("Compress")] Compress,
        [Description("Connect Develop")] Connectdevelop,
        [Description("Contao")] Contao,
        [Description("Copyright")] Copyright,
        [Description("Creative Commons")] CreativeCommons,
        [Description("credit-card")] CreditCard,
        [Description("Credit Card")] CreditCardAlt,
        [Description("crop")] Crop,
        [Description("Crosshairs")] Crosshairs,
        [Description("CSS 3 Logo")] Css3,
        [Description("Cube")] Cube,
        [Description("Cubes")] Cubes,
        [Description("Cutlery")] Cutlery,
        [Description("DashCube")] Dashcube,
        [Description("Database")] Database,
        [Description("Deaf (Deafness, HardOfHearing)")] Deaf,
        [Description("Delicious Logo")] Delicious,
        [Description("Desktop")] Desktop,
        [Description("deviantART")] Deviantart,
        [Description("Diamond")] Diamond,
        [Description("Digg Logo")] Digg,
        [Description("Dot Circle Outlined")] DotCircleOutline,
        [Description("Download")] Download,
        [Description("Dribbble")] Dribbble,
        [Description("Dropbox")] Dropbox,
        [Description("Drupal Logo")] Drupal,
        [Description("Edge Browser")] Edge,
        [Description("eject")] Eject,
        [Description("Ellipsis Horizontal")] EllipsisH,
        [Description("Ellipsis Vertical")] EllipsisV,
        [Description("Galactic Empire (Ge)")] Empire,
        [Description("Envelope")] Envelope,
        [Description("Envelope Outlined")] EnvelopeOutline,
        [Description("Envelope Square")] EnvelopeSquare,
        [Description("Envira Gallery")] Envira,
        [Description("eraser")] Eraser,
        [Description("Euro (EUR) (Euro)")] Eur,
        [Description("Exchange")] Exchange,
        [Description("exclamation")] Exclamation,
        [Description("Exclamation Circle")] ExclamationCircle,
        [Description("Exclamation Triangle (Warning)")] ExclamationTriangle,
        [Description("Expand")] Expand,
        [Description("ExpeditedSSL")] Expeditedssl,
        [Description("External Link")] ExternalLink,
        [Description("External Link Square")] ExternalLinkSquare,
        [Description("Eye")] Eye,
        [Description("Eyedropper")] Eyedropper,
        [Description("Eye Slash")] EyeSlash,
        [Description("Facebook (FacebookF)")] Facebook,
        [Description("Facebook Official")] FacebookOfficial,
        [Description("Facebook Square")] FacebookSquare,
        [Description("fast-backward")] FastBackward,
        [Description("fast-forward")] FastForward,
        [Description("Fax")] Fax,
        [Description("Female")] Female,
        [Description("fighter-jet")] FighterJet,
        [Description("File")] File,
        [Description("Archive File Outlined (FileZipOutline)")] FileArchiveOutline,
        [Description("Audio File Outlined (FileSoundOutline)")] FileAudioOutline,
        [Description("Code File Outlined")] FileCodeOutline,
        [Description("Excel File Outlined")] FileExcelOutline,
        [Description("Image File Outlined (FilePhotoOutline, FilePictureOutline)")] FileImageOutline,
        [Description("File Outlined")] FileOutline,
        [Description("PDF File Outlined")] FilePdfOutline,
        [Description("Powerpoint File Outlined")] FilePowerpointOutline,
        [Description("Files Outlined (Copy)")] FilesOutline,
        [Description("File Text")] FileText,
        [Description("File Text Outlined")] FileTextOutline,
        [Description("Video File Outlined (FileMovieOutline)")] FileVideoOutline,
        [Description("Word File Outlined")] FileWordOutline,
        [Description("Film")] Film,
        [Description("Filter")] Filter,
        [Description("fire")] Fire,
        [Description("fire-extinguisher")] FireExtinguisher,
        [Description("Firefox")] Firefox,
        [Description("First Order")] FirstOrder,
        [Description("flag")] Flag,
        [Description("flag-checkered")] FlagCheckered,
        [Description("Flag Outlined")] FlagOutline,
        [Description("Flask")] Flask,
        [Description("Flickr")] Flickr,
        [Description("Floppy Outlined (Save)")] FloppyOutline,
        [Description("Folder")] Folder,
        [Description("Folder Open")] FolderOpen,
        [Description("Folder Outlined")] FolderOutline,
        [Description("Folder Open Outlined")] FolderOutlinepenOutline,
        [Description("font")] Font,
        [Description("Font Awesome (Fa)")] FontAwesome,
        [Description("Fonticons")] Fonticons,
        [Description("Fort Awesome")] FortAwesome,
        [Description("Forumbee")] Forumbee,
        [Description("forward")] Forward,
        [Description("Foursquare")] Foursquare,
        [Description("Frown Outlined")] FrownOutline,
        [Description("Futbol Outlined (SoccerBallOutline)")] FutbolOutline,
        [Description("Gamepad")] Gamepad,
        [Description("Gavel (Legal)")] Gavel,
        [Description("GBP")] Gbp,
        [Description("Genderless")] Genderless,
        [Description("Get Pocket")] GetPocket,
        [Description("GG Currency")] Gg,
        [Description("GG Currency Circle")] GgCircle,
        [Description("gift")] Gift,
        [Description("Git")] Git,
        [Description("GitHub")] Github,
        [Description("GitHub Alt")] GithubAlt,
        [Description("GitHub Square")] GithubSquare,
        [Description("GitLab")] Gitlab,
        [Description("Git Square")] GitSquare,
        [Description("Glass")] Glass,
        [Description("Glide")] Glide,
        [Description("Glide G")] GlideG,
        [Description("Globe")] Globe,
        [Description("Google Logo")] Google,
        [Description("Google Plus")] GooglePlus,
        [Description("Google Plus Official (GooglePlusCircle)")] GooglePlusOfficial,
        [Description("Google Plus Square")] GooglePlusSquare,
        [Description("Google Wallet")] GoogleWallet,
        [Description("Graduation Cap (MortarBoard)")] GraduationCap,
        [Description("Gratipay (Gittip) (Gittip)")] Gratipay,
        [Description("Hacker News (YCombinatorSquare, YcSquare)")] HackerNews,
        [Description("Lizard (Hand)")] HandLizardOutline,
        [Description("Hand Outlined Down")] HandOutlineDown,
        [Description("Hand Outlined Left")] HandOutlineLeft,
        [Description("Hand Outlined Right")] HandOutlineRight,
        [Description("Hand Outlined Up")] HandOutlineUp,
        [Description("Paper (Hand) (HandStopOutline)")] HandPaperOutline,
        [Description("Hand Peace")] HandPeaceOutline,
        [Description("Hand Pointer")] HandPointerOutline,
        [Description("Rock (Hand) (HandGrabOutline)")] HandRockOutline,
        [Description("Scissors (Hand)")] HandScissorsOutline,
        [Description("Spock (Hand)")] HandSpockOutline,
        [Description("Hashtag")] Hashtag,
        [Description("HDD")] HddOutline,
        [Description("header")] Header,
        [Description("headphones")] Headphones,
        [Description("Heart")] Heart,
        [Description("Heartbeat")] Heartbeat,
        [Description("Heart Outlined")] HeartOutline,
        [Description("History")] History,
        [Description("home")] Home,
        [Description("hospital Outlined")] HospitalOutline,
        [Description("Hourglass")] Hourglass,
        [Description("Hourglass End (Hourglass3)")] HourglassEnd,
        [Description("Hourglass Half (Hourglass2)")] HourglassHalf,
        [Description("Hourglass Outlined")] HourglassOutline,
        [Description("Hourglass Start (Hourglass1)")] HourglassStart,
        [Description("Houzz")] Houzz,
        [Description("H Square")] HSquare,
        [Description("HTML 5 Logo")] Html5,
        [Description("I Beam Cursor")] ICursor,
        [Description("Shekel (ILS) (Shekel, Sheqel)")] Ils,
        [Description("inbox")] Inbox,
        [Description("Indent")] Indent,
        [Description("Industry")] Industry,
        [Description("Info")] Info,
        [Description("Info Circle")] InfoCircle,
        [Description("Indian Rupee (INR) (Rupee)")] Inr,
        [Description("Instagram")] Instagram,
        [Description("Internet-explorer")] InternetExplorer,
        [Description("ioxhost")] Ioxhost,
        [Description("italic")] Italic,
        [Description("Joomla Logo")] Joomla,
        [Description("Japanese Yen (JPY) (Cny, Rmb, Yen)")] Jpy,
        [Description("jsFiddle")] Jsfiddle,
        [Description("key")] Key,
        [Description("Keyboard Outlined")] KeyboardOutline,
        [Description("Korean Won (KRW) (Won)")] Krw,
        [Description("Language")] Language,
        [Description("Laptop")] Laptop,
        [Description("last.fm")] Lastfm,
        [Description("last.fm Square")] LastfmSquare,
        [Description("leaf")] Leaf,
        [Description("Leanpub")] Leanpub,
        [Description("Lemon Outlined")] LemonOutline,
        [Description("Level Down")] LevelDown,
        [Description("Level Up")] LevelUp,
        [Description("Life Ring (LifeBouy, LifeBuoy, LifeSaver, Support)")] LifeRing,
        [Description("Lightbulb Outlined")] LightbulbOutline,
        [Description("Line Chart")] LineChart,
        [Description("Link (Chain)")] Link,
        [Description("LinkedIn")] Linkedin,
        [Description("LinkedIn Square")] LinkedinSquare,
        [Description("Linux")] Linux,
        [Description("list")] List,
        [Description("list-alt")] ListAlt,
        [Description("list-ol")] ListOl,
        [Description("list-ul")] ListUl,
        [Description("location-arrow")] LocationArrow,
        [Description("lock")] Lock,
        [Description("Long Arrow Down")] LongArrowDown,
        [Description("Long Arrow Left")] LongArrowLeft,
        [Description("Long Arrow Right")] LongArrowRight,
        [Description("Long Arrow Up")] LongArrowUp,
        [Description("Low Vision")] LowVision,
        [Description("magic")] Magic,
        [Description("magnet")] Magnet,
        [Description("Male")] Male,
        [Description("Map")] Map,
        [Description("map-marker")] MapMarker,
        [Description("Map Outlined")] MapOutline,
        [Description("Map Pin")] MapPin,
        [Description("Map Signs")] MapSigns,
        [Description("Mars")] Mars,
        [Description("Mars Double")] MarsDouble,
        [Description("Mars Stroke")] MarsStroke,
        [Description("Mars Stroke Horizontal")] MarsStrokeH,
        [Description("Mars Stroke Vertical")] MarsStrokeV,
        [Description("MaxCDN")] Maxcdn,
        [Description("meanpath")] Meanpath,
        [Description("Medium")] Medium,
        [Description("medkit")] Medkit,
        [Description("Meh Outlined")] MehOutline,
        [Description("Mercury")] Mercury,
        [Description("microphone")] Microphone,
        [Description("Microphone Slash")] MicrophoneSlash,
        [Description("minus")] Minus,
        [Description("Minus Circle")] MinusCircle,
        [Description("Minus Square")] MinusSquare,
        [Description("Minus Square Outlined")] MinusSquareOutline,
        [Description("Mixcloud")] Mixcloud,
        [Description("Mobile Phone (MobilePhone)")] Mobile,
        [Description("MODX")] Modx,
        [Description("Money")] Money,
        [Description("Moon Outlined")] MoonOutline,
        [Description("Motorcycle")] Motorcycle,
        [Description("Mouse Pointer")] MousePointer,
        [Description("Music")] Music,
        [Description("Neuter")] Neuter,
        [Description("Newspaper Outlined")] NewspaperOutline,
        [Description("Object Group")] ObjectGroup,
        [Description("Object Ungroup")] ObjectUngroup,
        [Description("Odnoklassniki")] Odnoklassniki,
        [Description("Odnoklassniki Square")] OdnoklassnikiSquare,
        [Description("OpenCart")] Opencart,
        [Description("OpenID")] Openid,
        [Description("Opera")] Opera,
        [Description("Optin Monster")] OptinMonster,
        [Description("Outdent (Dedent)")] Outdent,
        [Description("Pagelines")] Pagelines,
        [Description("Paint Brush")] PaintBrush,
        [Description("Paperclip")] Paperclip,
        [Description("Paper Plane (Send)")] PaperPlane,
        [Description("Paper Plane Outlined (SendOutline)")] PaperPlaneOutline,
        [Description("paragraph")] Paragraph,
        [Description("pause")] Pause,
        [Description("Pause Circle")] PauseCircle,
        [Description("Pause Circle Outlined")] PauseCircleOutline,
        [Description("Paw")] Paw,
        [Description("Paypal")] Paypal,
        [Description("pencil")] Pencil,
        [Description("Pencil Square")] PencilSquare,
        [Description("Pencil Square Outlined (Edit)")] PencilSquareOutline,
        [Description("Percent")] Percent,
        [Description("Phone")] Phone,
        [Description("Phone Square")] PhoneSquare,
        [Description("Picture Outlined (Photo, Image)")] PictureOutline,
        [Description("Pie Chart")] PieChart,
        [Description("Pied Piper Logo")] PiedPiper,
        [Description("Pied Piper Alternate Logo")] PiedPiperAlt,
        [Description("Pied Piper PP Logo (Old)")] PiedPiperPp,
        [Description("Pinterest")] Pinterest,
        [Description("Pinterest P")] PinterestP,
        [Description("Pinterest Square")] PinterestSquare,
        [Description("plane")] Plane,
        [Description("play")] Play,
        [Description("Play Circle")] PlayCircle,
        [Description("Play Circle Outlined")] PlayCircleOutline,
        [Description("Plug")] Plug,
        [Description("plus")] Plus,
        [Description("Plus Circle")] PlusCircle,
        [Description("Plus Square")] PlusSquare,
        [Description("Plus Square Outlined")] PlusSquareOutline,
        [Description("Power Off")] PowerOff,
        [Description("print")] Print,
        [Description("Product Hunt")] ProductHunt,
        [Description("Puzzle Piece")] PuzzlePiece,
        [Description("QQ")] Qq,
        [Description("qrcode")] Qrcode,
        [Description("Question")] Question,
        [Description("Question Circle")] QuestionCircle,
        [Description("Question Circle Outlined")] QuestionCircleOutline,
        [Description("quote-left")] QuoteLeft,
        [Description("quote-right")] QuoteRight,
        [Description("random")] Random,
        [Description("Rebel Alliance (Ra, Resistance)")] Rebel,
        [Description("Recycle")] Recycle,
        [Description("reddit Logo")] Reddit,
        [Description("reddit Alien")] RedditAlien,
        [Description("reddit Square")] RedditSquare,
        [Description("refresh")] Refresh,
        [Description("Registered Trademark")] Registered,
        [Description("Renren")] Renren,
        [Description("Repeat (RotateRight)")] Repeat,
        [Description("Reply (MailReply)")] Reply,
        [Description("reply-all (MailReplyAll)")] ReplyAll,
        [Description("retweet")] Retweet,
        [Description("road")] Road,
        [Description("rocket")] Rocket,
        [Description("rss (Feed)")] Rss,
        [Description("RSS Square")] RssSquare,
        [Description("Russian Ruble (RUB) (Ruble, Rouble)")] Rub,
        [Description("Safari")] Safari,
        [Description("Scissors (Cut)")] Scissors,
        [Description("Scribd")] Scribd,
        [Description("Search")] Search,
        [Description("Search Minus")] SearchMinus,
        [Description("Search Plus")] SearchPlus,
        [Description("Sellsy")] Sellsy,
        [Description("Server")] Server,
        [Description("Share (MailForward)")] Share,
        [Description("Share Alt")] ShareAlt,
        [Description("Share Alt Square")] ShareAltSquare,
        [Description("Share Square")] ShareSquare,
        [Description("Share Square Outlined")] ShareSquareOutline,
        [Description("shield")] Shield,
        [Description("Ship")] Ship,
        [Description("Shirts in Bulk")] Shirtsinbulk,
        [Description("Shopping Bag")] ShoppingBag,
        [Description("Shopping Basket")] ShoppingBasket,
        [Description("shopping-cart")] ShoppingCart,
        [Description("signal")] Signal,
        [Description("Sign In")] SignIn,
        [Description("Sign Language (Signing)")] SignLanguage,
        [Description("Sign Out")] SignOut,
        [Description("SimplyBuilt")] Simplybuilt,
        [Description("Sitemap")] Sitemap,
        [Description("skyatlas")] Skyatlas,
        [Description("Skype")] Skype,
        [Description("Slack Logo")] Slack,
        [Description("Sliders")] Sliders,
        [Description("Slideshare")] Slideshare,
        [Description("Smile Outlined")] SmileOutline,
        [Description("Snapchat")] Snapchat,
        [Description("Snapchat Ghost")] SnapchatGhost,
        [Description("Snapchat Square")] SnapchatSquare,
        [Description("Sort (Unsorted)")] Sort,
        [Description("Sort Alpha Ascending")] SortAlphaAsc,
        [Description("Sort Alpha Descending")] SortAlphaDesc,
        [Description("Sort Amount Ascending")] SortAmountAsc,
        [Description("Sort Amount Descending")] SortAmountDesc,
        [Description("Sort Ascending (SortUp)")] SortAsc,
        [Description("Sort Descending (SortDown)")] SortDesc,
        [Description("Sort Numeric Ascending")] SortNumericAsc,
        [Description("Sort Numeric Descending")] SortNumericDesc,
        [Description("SoundCloud")] Soundcloud,
        [Description("Space Shuttle")] SpaceShuttle,
        [Description("Spinner")] Spinner,
        [Description("spoon")] Spoon,
        [Description("Spotify")] Spotify,
        [Description("Square")] Square,
        [Description("Square Outlined")] SquareOutline,
        [Description("Stack Exchange")] StackExchange,
        [Description("Stack Overflow")] StackOverflow,
        [Description("Star")] Star,
        [Description("star-half")] StarHalf,
        [Description("Star Half Outlined (StarHalfEmpty, StarHalfFull)")] StarHalfOutline,
        [Description("Star Outlined")] StarOutline,
        [Description("Steam")] Steam,
        [Description("Steam Square")] SteamSquare,
        [Description("step-backward")] StepBackward,
        [Description("step-forward")] StepForward,
        [Description("Stethoscope")] Stethoscope,
        [Description("Sticky Note")] StickyNote,
        [Description("Sticky Note Outlined")] StickyNoteOutline,
        [Description("stop")] Stop,
        [Description("Stop Circle")] StopCircle,
        [Description("Stop Circle Outlined")] StopCircleOutline,
        [Description("Street View")] StreetView,
        [Description("Strikethrough")] Strikethrough,
        [Description("StumbleUpon Logo")] Stumbleupon,
        [Description("StumbleUpon Circle")] StumbleuponCircle,
        [Description("subscript")] Subscript,
        [Description("Subway")] Subway,
        [Description("Suitcase")] Suitcase,
        [Description("Sun Outlined")] SunOutline,
        [Description("superscript")] Superscript,
        [Description("table")] Table,
        [Description("tablet")] Tablet,
        [Description("Tachometer (Dashboard)")] Tachometer,
        [Description("tag")] Tag,
        [Description("tags")] Tags,
        [Description("Tasks")] Tasks,
        [Description("Taxi (Cab)")] Taxi,
        [Description("Television (Tv)")] Television,
        [Description("Tencent Weibo")] TencentWeibo,
        [Description("Terminal")] Terminal,
        [Description("text-height")] TextHeight,
        [Description("text-width")] TextWidth,
        [Description("th")] Th,
        [Description("ThemeIsle")] Themeisle,
        [Description("th-large")] ThLarge,
        [Description("th-list")] ThList,
        [Description("thumbs-down")] ThumbsDown,
        [Description("Thumbs Down Outlined")] ThumbsOutlineDown,
        [Description("Thumbs Up Outlined")] ThumbsOutlineUp,
        [Description("thumbs-up")] ThumbsUp,
        [Description("Thumb Tack")] ThumbTack,
        [Description("Ticket")] Ticket,
        [Description("Times (Remove, Close)")] Times,
        [Description("Times Circle")] TimesCircle,
        [Description("Times Circle Outlined")] TimesCircleOutline,
        [Description("tint")] Tint,
        [Description("Toggle Off")] ToggleOff,
        [Description("Toggle On")] ToggleOn,
        [Description("Trademark")] Trademark,
        [Description("Train")] Train,
        [Description("Transgender (Intersex)")] Transgender,
        [Description("Transgender Alt")] TransgenderAlt,
        [Description("Trash")] Trash,
        [Description("Trash Outlined")] TrashOutline,
        [Description("Tree")] Tree,
        [Description("Trello")] Trello,
        [Description("TripAdvisor")] Tripadvisor,
        [Description("trophy")] Trophy,
        [Description("truck")] Truck,
        [Description("Turkish Lira (TRY) (TurkishLira)")] Try,
        [Description("TTY")] Tty,
        [Description("Tumblr")] Tumblr,
        [Description("Tumblr Square")] TumblrSquare,
        [Description("Twitch")] Twitch,
        [Description("Twitter")] Twitter,
        [Description("Twitter Square")] TwitterSquare,
        [Description("Umbrella")] Umbrella,
        [Description("Underline")] Underline,
        [Description("Undo (RotateLeft)")] Undo,
        [Description("Universal Access")] UniversalAccess,
        [Description("University (Institution, Bank)")] University,
        [Description("unlock")] Unlock,
        [Description("Unlock Alt")] UnlockAlt,
        [Description("Upload")] Upload,
        [Description("USB")] Usb,
        [Description("US Dollar (Dollar)")] Usd,
        [Description("User")] User,
        [Description("user-md")] UserMd,
        [Description("Add User")] UserPlus,
        [Description("Users (Group)")] Users,
        [Description("User Secret")] UserSecret,
        [Description("Remove User")] UserTimes,
        [Description("Venus")] Venus,
        [Description("Venus Double")] VenusDouble,
        [Description("Venus Mars")] VenusMars,
        [Description("Viacoin")] Viacoin,
        [Description("Viadeo")] Viadeo,
        [Description("Viadeo Square")] ViadeoSquare,
        [Description("Video Camera")] VideoCamera,
        [Description("Vimeo")] Vimeo,
        [Description("Vimeo Square")] VimeoSquare,
        [Description("Vine")] Vine,
        [Description("VK")] Vk,
        [Description("Volume Control Phone")] VolumeControlPhone,
        [Description("volume-down")] VolumeDown,
        [Description("volume-off")] VolumeOff,
        [Description("volume-up")] VolumeUp,
        [Description("Weibo")] Weibo,
        [Description("Weixin (WeChat) (Wechat)")] Weixin,
        [Description("What's App")] Whatsapp,
        [Description("Wheelchair")] Wheelchair,
        [Description("Wheelchair Alt")] WheelchairAlt,
        [Description("WiFi")] Wifi,
        [Description("Wikipedia W")] WikipediaW,
        [Description("Windows")] Windows,
        [Description("WordPress Logo")] Wordpress,
        [Description("WPBeginner")] Wpbeginner,
        [Description("WPForms")] Wpforms,
        [Description("Wrench")] Wrench,
        [Description("Xing")] Xing,
        [Description("Xing Square")] XingSquare,
        [Description("Yahoo Logo")] Yahoo,
        [Description("Y Combinator (Yc)")] YCombinator,
        [Description("Yelp")] Yelp,
        [Description("Yoast")] Yoast,
        [Description("YouTube")] Youtube,
        [Description("YouTube Play")] YoutubePlay,
        [Description("YouTube Square")] YoutubeSquare,
    }
}