namespace MahApps.Metro.Controls
{
    using System.ComponentModel;

    /// ******************************************
    /// This code is auto generated. Do not amend.
    /// ******************************************

    /// <summary>
    /// List of available icons for use with <see cref="PackIconEntypo" />.
    /// </summary>
    /// <remarks>
    /// All icons sourced from Entypo+ Icons Font - <see><cref>http://www.entypo.com</cref></see> - 
    /// <see><cref>http://creativecommons.org/licenses/by-sa/4.0/</cref></see>.
    /// </remarks>
    public enum PackIconEntypoKind
    {
        [Description("500px (Social Extension)")] _500px,
        [Description("500px-with-circle (Social Extension)")] _500pxWithCircle,
        [Description("address")] Address,
        [Description("add-to-list")] AddToList,
        [Description("add-user")] AddUser,
        [Description("adjust")] Adjust,
        [Description("air")] Air,
        [Description("aircraft")] Aircraft,
        [Description("aircraft-landing")] AircraftLanding,
        [Description("aircraft-take-off")] AircraftTakeOff,
        [Description("align-bottom")] AlignBottom,
        [Description("align-horizontal-middle")] AlignHorizontalMiddle,
        [Description("align-left")] AlignLeft,
        [Description("align-right")] AlignRight,
        [Description("align-top")] AlignTop,
        [Description("align-vertical-middle")] AlignVerticalMiddle,
        [Description("app-store (Social Extension)")] AppStore,
        [Description("archive")] Archive,
        [Description("area-graph")] AreaGraph,
        [Description("arrow-bold-down")] ArrowBoldDown,
        [Description("arrow-bold-left")] ArrowBoldLeft,
        [Description("arrow-bold-right")] ArrowBoldRight,
        [Description("arrow-bold-up")] ArrowBoldUp,
        [Description("arrow-down")] ArrowDown,
        [Description("arrow-left")] ArrowLeft,
        [Description("arrow-long-down")] ArrowLongDown,
        [Description("arrow-long-left")] ArrowLongLeft,
        [Description("arrow-long-right")] ArrowLongRight,
        [Description("arrow-long-up")] ArrowLongUp,
        [Description("arrow-right")] ArrowRight,
        [Description("arrow-up")] ArrowUp,
        [Description("arrow-with-circle-down")] ArrowWithCircleDown,
        [Description("arrow-with-circle-left")] ArrowWithCircleLeft,
        [Description("arrow-with-circle-right")] ArrowWithCircleRight,
        [Description("arrow-with-circle-up")] ArrowWithCircleUp,
        [Description("attachment")] Attachment,
        [Description("awareness-ribbon")] AwarenessRibbon,
        [Description("back")] Back,
        [Description("back-in-time")] BackInTime,
        [Description("baidu (Social Extension)")] Baidu,
        [Description("bar-graph")] BarGraph,
        [Description("basecamp (Social Extension)")] Basecamp,
        [Description("battery")] Battery,
        [Description("beamed-note")] BeamedNote,
        [Description("behance (Social Extension)")] Behance,
        [Description("bell")] Bell,
        [Description("blackboard")] Blackboard,
        [Description("block")] Block,
        [Description("book")] Book,
        [Description("bookmark")] Bookmark,
        [Description("bookmarks")] Bookmarks,
        [Description("bowl")] Bowl,
        [Description("box")] Box,
        [Description("briefcase")] Briefcase,
        [Description("browser")] Browser,
        [Description("brush")] Brush,
        [Description("bucket")] Bucket,
        [Description("bug")] Bug,
        [Description("cake")] Cake,
        [Description("calculator")] Calculator,
        [Description("calendar")] Calendar,
        [Description("camera")] Camera,
        [Description("ccw")] Ccw,
        [Description("chat")] Chat,
        [Description("check")] Check,
        [Description("chevron-down")] ChevronDown,
        [Description("chevron-left")] ChevronLeft,
        [Description("chevron-right")] ChevronRight,
        [Description("chevron-small-down")] ChevronSmallDown,
        [Description("chevron-small-left")] ChevronSmallLeft,
        [Description("chevron-small-right")] ChevronSmallRight,
        [Description("chevron-small-up")] ChevronSmallUp,
        [Description("chevron-thin-down")] ChevronThinDown,
        [Description("chevron-thin-left")] ChevronThinLeft,
        [Description("chevron-thin-right")] ChevronThinRight,
        [Description("chevron-thin-up")] ChevronThinUp,
        [Description("chevron-up")] ChevronUp,
        [Description("chevron-with-circle-down")] ChevronWithCircleDown,
        [Description("chevron-with-circle-left")] ChevronWithCircleLeft,
        [Description("chevron-with-circle-right")] ChevronWithCircleRight,
        [Description("chevron-with-circle-up")] ChevronWithCircleUp,
        [Description("circle")] Circle,
        [Description("circle-with-cross")] CircleWithCross,
        [Description("circle-with-minus")] CircleWithMinus,
        [Description("circle-with-plus")] CircleWithPlus,
        [Description("circular-graph")] CircularGraph,
        [Description("clapperboard")] Clapperboard,
        [Description("classic-computer")] ClassicComputer,
        [Description("clipboard")] Clipboard,
        [Description("clock")] Clock,
        [Description("cloud")] Cloud,
        [Description("code")] Code,
        [Description("cog")] Cog,
        [Description("colours")] Colours,
        [Description("compass")] Compass,
        [Description("controller-fast-backward")] ControllerFastBackward,
        [Description("controller-fast-forward")] ControllerFastForward,
        [Description("controller-jump-to-start")] ControllerJumpToStart,
        [Description("controller-next")] ControllerNext,
        [Description("controller-paus")] ControllerPaus,
        [Description("controller-play")] ControllerPlay,
        [Description("controller-record")] ControllerRecord,
        [Description("controller-stop")] ControllerStop,
        [Description("controller-volume")] ControllerVolume,
        [Description("copy")] Copy,
        [Description("creative-cloud (Social Extension)")] CreativeCloud,
        [Description("creative-commons")] CreativeCommons,
        [Description("creative-commons-attribution")] CreativeCommonsAttribution,
        [Description("creative-commons-noderivs")] CreativeCommonsNoderivs,
        [Description("creative-commons-noncommercial-eu")] CreativeCommonsNoncommercialEu,
        [Description("creative-commons-noncommercial-us")] CreativeCommonsNoncommercialUs,
        [Description("creative-commons-public-domain")] CreativeCommonsPublicDomain,
        [Description("creative-commons-remix")] CreativeCommonsRemix,
        [Description("creative-commons-share")] CreativeCommonsShare,
        [Description("creative-commons-sharealike")] CreativeCommonsSharealike,
        [Description("credit")] Credit,
        [Description("credit-card")] CreditCard,
        [Description("crop")] Crop,
        [Description("cross")] Cross,
        [Description("cup")] Cup,
        [Description("cw")] Cw,
        [Description("cycle")] Cycle,
        [Description("database")] Database,
        [Description("dial-pad")] DialPad,
        [Description("direction")] Direction,
        [Description("document")] Document,
        [Description("document-landscape")] DocumentLandscape,
        [Description("documents")] Documents,
        [Description("dot-single")] DotSingle,
        [Description("dots-three-horizontal")] DotsThreeHorizontal,
        [Description("dots-three-vertical")] DotsThreeVertical,
        [Description("dots-two-horizontal")] DotsTwoHorizontal,
        [Description("dots-two-vertical")] DotsTwoVertical,
        [Description("download")] Download,
        [Description("dribbble (Social Extension)")] Dribbble,
        [Description("dribbble-with-circle (Social Extension)")] DribbbleWithCircle,
        [Description("drink")] Drink,
        [Description("drive")] Drive,
        [Description("drop")] Drop,
        [Description("dropbox (Social Extension)")] Dropbox,
        [Description("edit")] Edit,
        [Description("email")] Email,
        [Description("emoji-flirt")] EmojiFlirt,
        [Description("emoji-happy")] EmojiHappy,
        [Description("emoji-neutral")] EmojiNeutral,
        [Description("emoji-sad")] EmojiSad,
        [Description("erase")] Erase,
        [Description("eraser")] Eraser,
        [Description("evernote (Social Extension)")] Evernote,
        [Description("export")] Export,
        [Description("eye")] Eye,
        [Description("eye-with-line")] EyeWithLine,
        [Description("facebook (Social Extension)")] Facebook,
        [Description("facebook-with-circle (Social Extension)")] FacebookWithCircle,
        [Description("feather")] Feather,
        [Description("fingerprint")] Fingerprint,
        [Description("flag")] Flag,
        [Description("flash")] Flash,
        [Description("flashlight")] Flashlight,
        [Description("flat-brush")] FlatBrush,
        [Description("flattr (Social Extension)")] Flattr,
        [Description("flickr (Social Extension)")] Flickr,
        [Description("flickr-with-circle (Social Extension)")] FlickrWithCircle,
        [Description("flow-branch")] FlowBranch,
        [Description("flow-cascade")] FlowCascade,
        [Description("flower")] Flower,
        [Description("flow-line")] FlowLine,
        [Description("flow-parallel")] FlowParallel,
        [Description("flow-tree")] FlowTree,
        [Description("folder")] Folder,
        [Description("folder-images")] FolderImages,
        [Description("folder-music")] FolderMusic,
        [Description("folder-video")] FolderVideo,
        [Description("forward")] Forward,
        [Description("foursquare (Social Extension)")] Foursquare,
        [Description("funnel")] Funnel,
        [Description("game-controller")] GameController,
        [Description("gauge")] Gauge,
        [Description("github (Social Extension)")] Github,
        [Description("github-with-circle (Social Extension)")] GithubWithCircle,
        [Description("globe")] Globe,
        [Description("google-drive (Social Extension)")] GoogleDrive,
        [Description("google-hangouts (Social Extension)")] GoogleHangouts,
        [Description("google-play (Social Extension)")] GooglePlay,
        [Description("google+ (Social Extension)")] Googleplus,
        [Description("google+-with-circle (Social Extension)")] GoogleplusWithCircle,
        [Description("graduation-cap")] GraduationCap,
        [Description("grid")] Grid,
        [Description("grooveshark (Social Extension)")] Grooveshark,
        [Description("hair-cross")] HairCross,
        [Description("hand")] Hand,
        [Description("heart")] Heart,
        [Description("heart-outlined")] HeartOutlined,
        [Description("help")] Help,
        [Description("help-with-circle")] HelpWithCircle,
        [Description("home")] Home,
        [Description("hour-glass")] HourGlass,
        [Description("houzz (Social Extension)")] Houzz,
        [Description("icloud (Social Extension)")] Icloud,
        [Description("image")] Image,
        [Description("image-inverted")] ImageInverted,
        [Description("images")] Images,
        [Description("inbox")] Inbox,
        [Description("infinity")] Infinity,
        [Description("info")] Info,
        [Description("info-with-circle")] InfoWithCircle,
        [Description("instagram (Social Extension)")] Instagram,
        [Description("install")] Install,
        [Description("key")] Key,
        [Description("keyboard")] Keyboard,
        [Description("lab-flask")] LabFlask,
        [Description("landline")] Landline,
        [Description("language")] Language,
        [Description("laptop")] Laptop,
        [Description("lastfm (Social Extension)")] Lastfm,
        [Description("lastfm-with-circle (Social Extension)")] LastfmWithCircle,
        [Description("layers")] Layers,
        [Description("leaf")] Leaf,
        [Description("level-down")] LevelDown,
        [Description("level-up")] LevelUp,
        [Description("lifebuoy")] Lifebuoy,
        [Description("light-bulb")] LightBulb,
        [Description("light-down")] LightDown,
        [Description("light-up")] LightUp,
        [Description("line-graph")] LineGraph,
        [Description("link")] Link,
        [Description("linkedin (Social Extension)")] Linkedin,
        [Description("linkedin-with-circle (Social Extension)")] LinkedinWithCircle,
        [Description("list")] List,
        [Description("location")] Location,
        [Description("location-pin")] LocationPin,
        [Description("lock")] Lock,
        [Description("lock-open")] LockOpen,
        [Description("login")] Login,
        [Description("log-out")] LogOut,
        [Description("loop")] Loop,
        [Description("magnet")] Magnet,
        [Description("magnifying-glass")] MagnifyingGlass,
        [Description("mail")] Mail,
        [Description("mail-with-circle (Social Extension)")] MailWithCircle,
        [Description("man")] Man,
        [Description("map")] Map,
        [Description("mask")] Mask,
        [Description("medal")] Medal,
        [Description("medium (Social Extension)")] Medium,
        [Description("medium-with-circle (Social Extension)")] MediumWithCircle,
        [Description("megaphone")] Megaphone,
        [Description("menu")] Menu,
        [Description("merge")] Merge,
        [Description("message")] Message,
        [Description("mic")] Mic,
        [Description("minus")] Minus,
        [Description("mixi (Social Extension)")] Mixi,
        [Description("mobile")] Mobile,
        [Description("modern-mic")] ModernMic,
        [Description("moon")] Moon,
        [Description("mouse")] Mouse,
        [Description("mouse-pointer")] MousePointer,
        [Description("music")] Music,
        [Description("network")] Network,
        [Description("new")] New,
        [Description("new-message")] NewMessage,
        [Description("news")] News,
        [Description("newsletter")] Newsletter,
        [Description("note")] Note,
        [Description("notification")] Notification,
        [Description("notifications-off")] NotificationsOff,
        [Description("old-mobile")] OldMobile,
        [Description("old-phone")] OldPhone,
        [Description("onedrive (Social Extension)")] Onedrive,
        [Description("open-book")] OpenBook,
        [Description("palette")] Palette,
        [Description("paper-plane")] PaperPlane,
        [Description("paypal (Social Extension)")] Paypal,
        [Description("pencil")] Pencil,
        [Description("phone")] Phone,
        [Description("picasa (Social Extension)")] Picasa,
        [Description("pie-chart")] PieChart,
        [Description("pin")] Pin,
        [Description("pinterest (Social Extension)")] Pinterest,
        [Description("pinterest-with-circle (Social Extension)")] PinterestWithCircle,
        [Description("plus")] Plus,
        [Description("popup")] Popup,
        [Description("power-plug")] PowerPlug,
        [Description("price-ribbon")] PriceRibbon,
        [Description("price-tag")] PriceTag,
        [Description("print")] Print,
        [Description("progress-empty")] ProgressEmpty,
        [Description("progress-full")] ProgressFull,
        [Description("progress-one")] ProgressOne,
        [Description("progress-two")] ProgressTwo,
        [Description("publish")] Publish,
        [Description("qq (Social Extension)")] Qq,
        [Description("qq-with-circle (Social Extension)")] QqWithCircle,
        [Description("quote")] Quote,
        [Description("radio")] Radio,
        [Description("raft (Social Extension)")] Raft,
        [Description("raft-with-circle (Social Extension)")] RaftWithCircle,
        [Description("rainbow (Social Extension)")] Rainbow,
        [Description("rdio (Social Extension)")] Rdio,
        [Description("rdio-with-circle (Social Extension)")] RdioWithCircle,
        [Description("remove-user")] RemoveUser,
        [Description("renren (Social Extension)")] Renren,
        [Description("reply")] Reply,
        [Description("reply-all")] ReplyAll,
        [Description("resize-100%")] Resize100%,
        [Description("resize-full-screen")] ResizeFullScreen,
        [Description("retweet")] Retweet,
        [Description("rocket")] Rocket,
        [Description("round-brush")] RoundBrush,
        [Description("rss")] Rss,
        [Description("ruler")] Ruler,
        [Description("save")] Save,
        [Description("scissors")] Scissors,
        [Description("scribd (Social Extension)")] Scribd,
        [Description("select-arrows")] SelectArrows,
        [Description("share")] Share,
        [Description("shareable")] Shareable,
        [Description("share-alternative")] ShareAlternative,
        [Description("shield")] Shield,
        [Description("shop")] Shop,
        [Description("shopping-bag")] ShoppingBag,
        [Description("shopping-basket")] ShoppingBasket,
        [Description("shopping-cart")] ShoppingCart,
        [Description("shuffle")] Shuffle,
        [Description("signal")] Signal,
        [Description("sina-weibo (Social Extension)")] SinaWeibo,
        [Description("skype (Social Extension)")] Skype,
        [Description("skype-with-circle (Social Extension)")] SkypeWithCircle,
        [Description("slideshare (Social Extension)")] Slideshare,
        [Description("smashing (Social Extension)")] Smashing,
        [Description("sound")] Sound,
        [Description("soundcloud (Social Extension)")] Soundcloud,
        [Description("sound-mix")] SoundMix,
        [Description("sound-mute")] SoundMute,
        [Description("sports-club")] SportsClub,
        [Description("spotify (Social Extension)")] Spotify,
        [Description("spotify-with-circle (Social Extension)")] SpotifyWithCircle,
        [Description("spreadsheet")] Spreadsheet,
        [Description("squared-cross")] SquaredCross,
        [Description("squared-minus")] SquaredMinus,
        [Description("squared-plus")] SquaredPlus,
        [Description("star")] Star,
        [Description("star-outlined")] StarOutlined,
        [Description("stopwatch")] Stopwatch,
        [Description("stumbleupon (Social Extension)")] Stumbleupon,
        [Description("stumbleupon-with-circle (Social Extension)")] StumbleuponWithCircle,
        [Description("suitcase")] Suitcase,
        [Description("swap")] Swap,
        [Description("swarm (Social Extension)")] Swarm,
        [Description("sweden")] Sweden,
        [Description("switch")] Switch,
        [Description("tablet")] Tablet,
        [Description("tablet-mobile-combo")] TabletMobileCombo,
        [Description("tag")] Tag,
        [Description("text")] Text,
        [Description("text-document")] TextDocument,
        [Description("text-document-inverted")] TextDocumentInverted,
        [Description("thermometer")] Thermometer,
        [Description("thumbs-down")] ThumbsDown,
        [Description("thumbs-up")] ThumbsUp,
        [Description("thunder-cloud")] ThunderCloud,
        [Description("ticket")] Ticket,
        [Description("time-slot")] TimeSlot,
        [Description("tools")] Tools,
        [Description("traffic-cone")] TrafficCone,
        [Description("trash")] Trash,
        [Description("tree")] Tree,
        [Description("triangle-down")] TriangleDown,
        [Description("triangle-left")] TriangleLeft,
        [Description("triangle-right")] TriangleRight,
        [Description("triangle-up")] TriangleUp,
        [Description("tripadvisor (Social Extension)")] Tripadvisor,
        [Description("trophy")] Trophy,
        [Description("tumblr (Social Extension)")] Tumblr,
        [Description("tumblr-with-circle (Social Extension)")] TumblrWithCircle,
        [Description("tv")] Tv,
        [Description("twitter (Social Extension)")] Twitter,
        [Description("twitter-with-circle (Social Extension)")] TwitterWithCircle,
        [Description("typing")] Typing,
        [Description("uninstall")] Uninstall,
        [Description("unread")] Unread,
        [Description("untag")] Untag,
        [Description("upload")] Upload,
        [Description("upload-to-cloud")] UploadToCloud,
        [Description("user")] User,
        [Description("users")] Users,
        [Description("v-card")] VCard,
        [Description("video")] Video,
        [Description("video-camera")] VideoCamera,
        [Description("vimeo (Social Extension)")] Vimeo,
        [Description("vimeo-with-circle (Social Extension)")] VimeoWithCircle,
        [Description("vine (Social Extension)")] Vine,
        [Description("vine-with-circle (Social Extension)")] VineWithCircle,
        [Description("vinyl")] Vinyl,
        [Description("vk (Social Extension)")] Vk,
        [Description("vk-alternitive (Social Extension)")] VkAlternitive,
        [Description("vk-with-circle (Social Extension)")] VkWithCircle,
        [Description("voicemail")] Voicemail,
        [Description("wallet")] Wallet,
        [Description("warning")] Warning,
        [Description("water")] Water,
        [Description("windows-store (Social Extension)")] WindowsStore,
        [Description("xing (Social Extension)")] Xing,
        [Description("xing-with-circle (Social Extension)")] XingWithCircle,
        [Description("yelp (Social Extension)")] Yelp,
        [Description("youko (Social Extension)")] Youko,
        [Description("youko-with-circle (Social Extension)")] YoukoWithCircle,
        [Description("youtube (Social Extension)")] Youtube,
        [Description("youtube-with-circle (Social Extension)")] YoutubeWithCircle,
    }
}