// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using System;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media.Animation;

namespace MahApps.Metro.Controls
{
    /// <summary>
    ///     A special animation used to animates the length of a <see cref="Grid" />.
    /// </summary>
    /// <seealso cref="System.Windows.Media.Animation.AnimationTimeline" />
    /// <autogeneratedoc />
    public class GridLengthAnimation : AnimationTimeline
    {
        /// <summary>Identifies the <see cref="From"/> dependency property.</summary>
        public static readonly DependencyProperty FromProperty
            = DependencyProperty.Register(nameof(From),
                                          typeof(GridLength),
                                          typeof(GridLengthAnimation));

        /// <summary>
        /// Gets or sets the length the animation starts at. Where it is not set, the animation goes to its
        /// destination at once instead of counting up to it.
        /// </summary>
        public GridLength From
        {
            get => (GridLength)this.GetValue(FromProperty);
            set => this.SetValue(FromProperty, value);
        }

        /// <summary>Identifies the <see cref="To"/> dependency property.</summary>
        public static readonly DependencyProperty ToProperty
            = DependencyProperty.Register(nameof(To),
                                          typeof(GridLength),
                                          typeof(GridLengthAnimation));

        /// <summary>
        /// Gets or sets the length the animation ends at.
        /// </summary>
        public GridLength To
        {
            get => (GridLength)this.GetValue(ToProperty);
            set => this.SetValue(ToProperty, value);
        }

        /// <inheritdoc />
        public override Type TargetPropertyType => typeof(GridLength);

        /// <inheritdoc />
        public override object GetCurrentValue(object defaultOriginValue, object defaultDestinationValue, AnimationClock animationClock)
        {
            if (ReadLength(this.GetValue(ToProperty), defaultDestinationValue) is not { } to)
            {
                return defaultDestinationValue;
            }

            if (ReadLength(this.GetValue(FromProperty), null) is not { } from || from.GridUnitType != to.GridUnitType)
            {
                // nothing to count from, or two kinds of length that have no way between them, so the destination at once
                return to;
            }

            return new GridLength(from.Value + ((to.Value - from.Value) * animationClock.CurrentProgress.GetValueOrDefault()), to.GridUnitType);
        }

        /// <summary>
        /// The length a property of this animation holds, or the one the property system already has where it holds none.
        ///
        /// <remarks>
        /// A <see cref="GridLength"/> nobody has set reads as Auto, and so does one whose binding has nothing to give yet.
        /// Auto is not a length to count with either way, so the answer is what the animated property is worth without
        /// this animation rather than a number made up here. Making one up is what turned a pane that had not got its
        /// length yet into a column of "*", which took half the control and stayed there.
        /// </remarks>
        /// </summary>
        private static GridLength? ReadLength(object? value, object? fallback)
        {
            if (value is GridLength length && !length.IsAuto)
            {
                return length;
            }

            return fallback is GridLength fallbackLength ? fallbackLength : null;
        }

        protected override Freezable CreateInstanceCore()
        {
            return new GridLengthAnimation();
        }
    }
}