//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahApps.Metro.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Automation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Automation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MahApps.Metro.Lang.Automation", typeof(Automation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog bottom.
        /// </summary>
        public static string DialogBottom {
            get {
                return ResourceManager.GetString("DialogBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog content.
        /// </summary>
        public static string DialogContent {
            get {
                return ResourceManager.GetString("DialogContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog icon.
        /// </summary>
        public static string DialogIcon {
            get {
                return ResourceManager.GetString("DialogIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog title.
        /// </summary>
        public static string DialogTitle {
            get {
                return ResourceManager.GetString("DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog top.
        /// </summary>
        public static string DialogTop {
            get {
                return ResourceManager.GetString("DialogTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string Maximize {
            get {
                return ResourceManager.GetString("Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu items.
        /// </summary>
        public static string MenuItems {
            get {
                return ResourceManager.GetString("MenuItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option items.
        /// </summary>
        public static string OptionItems {
            get {
                return ResourceManager.GetString("OptionItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll down.
        /// </summary>
        public static string ScrollDown {
            get {
                return ResourceManager.GetString("ScrollDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll left.
        /// </summary>
        public static string ScrollLeft {
            get {
                return ResourceManager.GetString("ScrollLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll right.
        /// </summary>
        public static string ScrollRight {
            get {
                return ResourceManager.GetString("ScrollRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll up.
        /// </summary>
        public static string ScrollUp {
            get {
                return ResourceManager.GetString("ScrollUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Calendar.
        /// </summary>
        public static string ShowCalendar {
            get {
                return ResourceManager.GetString("ShowCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Clock.
        /// </summary>
        public static string ShowClock {
            get {
                return ResourceManager.GetString("ShowClock", resourceCulture);
            }
        }
    }
}
