//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahApps.Metro.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ColorNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ColorNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MahApps.Metro.Lang.ColorNames", typeof(ColorNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alice Blue.
        /// </summary>
        internal static string AliceBlue {
            get {
                return ResourceManager.GetString("AliceBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amber.
        /// </summary>
        internal static string Amber {
            get {
                return ResourceManager.GetString("Amber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antique White.
        /// </summary>
        internal static string AntiqueWhite {
            get {
                return ResourceManager.GetString("AntiqueWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aqua.
        /// </summary>
        internal static string Aqua {
            get {
                return ResourceManager.GetString("Aqua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquamarine.
        /// </summary>
        internal static string Aquamarine {
            get {
                return ResourceManager.GetString("Aquamarine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure.
        /// </summary>
        internal static string Azure {
            get {
                return ResourceManager.GetString("Azure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beige.
        /// </summary>
        internal static string Beige {
            get {
                return ResourceManager.GetString("Beige", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bisque.
        /// </summary>
        internal static string Bisque {
            get {
                return ResourceManager.GetString("Bisque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        internal static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blanched Almond.
        /// </summary>
        internal static string BlanchedAlmond {
            get {
                return ResourceManager.GetString("BlanchedAlmond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Violet.
        /// </summary>
        internal static string BlueViolet {
            get {
                return ResourceManager.GetString("BlueViolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brown.
        /// </summary>
        internal static string Brown {
            get {
                return ResourceManager.GetString("Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burly Wood.
        /// </summary>
        internal static string BurlyWood {
            get {
                return ResourceManager.GetString("BurlyWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadet Blue.
        /// </summary>
        internal static string CadetBlue {
            get {
                return ResourceManager.GetString("CadetBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chartreuse.
        /// </summary>
        internal static string Chartreuse {
            get {
                return ResourceManager.GetString("Chartreuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chocolate.
        /// </summary>
        internal static string Chocolate {
            get {
                return ResourceManager.GetString("Chocolate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobalt.
        /// </summary>
        internal static string Cobalt {
            get {
                return ResourceManager.GetString("Cobalt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coral.
        /// </summary>
        internal static string Coral {
            get {
                return ResourceManager.GetString("Coral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cornflower Blue.
        /// </summary>
        internal static string CornflowerBlue {
            get {
                return ResourceManager.GetString("CornflowerBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cornsilk.
        /// </summary>
        internal static string Cornsilk {
            get {
                return ResourceManager.GetString("Cornsilk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crimson.
        /// </summary>
        internal static string Crimson {
            get {
                return ResourceManager.GetString("Crimson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyan.
        /// </summary>
        internal static string Cyan {
            get {
                return ResourceManager.GetString("Cyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Blue.
        /// </summary>
        internal static string DarkBlue {
            get {
                return ResourceManager.GetString("DarkBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Cyan.
        /// </summary>
        internal static string DarkCyan {
            get {
                return ResourceManager.GetString("DarkCyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Goldenrod.
        /// </summary>
        internal static string DarkGoldenrod {
            get {
                return ResourceManager.GetString("DarkGoldenrod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Gray.
        /// </summary>
        internal static string DarkGray {
            get {
                return ResourceManager.GetString("DarkGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Green.
        /// </summary>
        internal static string DarkGreen {
            get {
                return ResourceManager.GetString("DarkGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Khaki.
        /// </summary>
        internal static string DarkKhaki {
            get {
                return ResourceManager.GetString("DarkKhaki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Magenta.
        /// </summary>
        internal static string DarkMagenta {
            get {
                return ResourceManager.GetString("DarkMagenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Olive Green.
        /// </summary>
        internal static string DarkOliveGreen {
            get {
                return ResourceManager.GetString("DarkOliveGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Orange.
        /// </summary>
        internal static string DarkOrange {
            get {
                return ResourceManager.GetString("DarkOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Orchid.
        /// </summary>
        internal static string DarkOrchid {
            get {
                return ResourceManager.GetString("DarkOrchid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Red.
        /// </summary>
        internal static string DarkRed {
            get {
                return ResourceManager.GetString("DarkRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Salmon.
        /// </summary>
        internal static string DarkSalmon {
            get {
                return ResourceManager.GetString("DarkSalmon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Sea Green.
        /// </summary>
        internal static string DarkSeaGreen {
            get {
                return ResourceManager.GetString("DarkSeaGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Slate Blue.
        /// </summary>
        internal static string DarkSlateBlue {
            get {
                return ResourceManager.GetString("DarkSlateBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Slate Gray.
        /// </summary>
        internal static string DarkSlateGray {
            get {
                return ResourceManager.GetString("DarkSlateGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Turquoise.
        /// </summary>
        internal static string DarkTurquoise {
            get {
                return ResourceManager.GetString("DarkTurquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Violet.
        /// </summary>
        internal static string DarkViolet {
            get {
                return ResourceManager.GetString("DarkViolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep Pink.
        /// </summary>
        internal static string DeepPink {
            get {
                return ResourceManager.GetString("DeepPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep Sky Blue.
        /// </summary>
        internal static string DeepSkyBlue {
            get {
                return ResourceManager.GetString("DeepSkyBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dim Gray.
        /// </summary>
        internal static string DimGray {
            get {
                return ResourceManager.GetString("DimGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodger Blue.
        /// </summary>
        internal static string DodgerBlue {
            get {
                return ResourceManager.GetString("DodgerBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emerald.
        /// </summary>
        internal static string Emerald {
            get {
                return ResourceManager.GetString("Emerald", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firebrick.
        /// </summary>
        internal static string Firebrick {
            get {
                return ResourceManager.GetString("Firebrick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floral White.
        /// </summary>
        internal static string FloralWhite {
            get {
                return ResourceManager.GetString("FloralWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forest Green.
        /// </summary>
        internal static string ForestGreen {
            get {
                return ResourceManager.GetString("ForestGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuchsia.
        /// </summary>
        internal static string Fuchsia {
            get {
                return ResourceManager.GetString("Fuchsia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gainsboro.
        /// </summary>
        internal static string Gainsboro {
            get {
                return ResourceManager.GetString("Gainsboro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghost White.
        /// </summary>
        internal static string GhostWhite {
            get {
                return ResourceManager.GetString("GhostWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        internal static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goldenrod.
        /// </summary>
        internal static string Goldenrod {
            get {
                return ResourceManager.GetString("Goldenrod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        internal static string Gray {
            get {
                return ResourceManager.GetString("Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Yellow.
        /// </summary>
        internal static string GreenYellow {
            get {
                return ResourceManager.GetString("GreenYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honeydew.
        /// </summary>
        internal static string Honeydew {
            get {
                return ResourceManager.GetString("Honeydew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot Pink.
        /// </summary>
        internal static string HotPink {
            get {
                return ResourceManager.GetString("HotPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indian Red.
        /// </summary>
        internal static string IndianRed {
            get {
                return ResourceManager.GetString("IndianRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indigo.
        /// </summary>
        internal static string Indigo {
            get {
                return ResourceManager.GetString("Indigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ivory.
        /// </summary>
        internal static string Ivory {
            get {
                return ResourceManager.GetString("Ivory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khaki.
        /// </summary>
        internal static string Khaki {
            get {
                return ResourceManager.GetString("Khaki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lavender.
        /// </summary>
        internal static string Lavender {
            get {
                return ResourceManager.GetString("Lavender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lavender Blush.
        /// </summary>
        internal static string LavenderBlush {
            get {
                return ResourceManager.GetString("LavenderBlush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lawn Green.
        /// </summary>
        internal static string LawnGreen {
            get {
                return ResourceManager.GetString("LawnGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lemon Chiffon.
        /// </summary>
        internal static string LemonChiffon {
            get {
                return ResourceManager.GetString("LemonChiffon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Blue.
        /// </summary>
        internal static string LightBlue {
            get {
                return ResourceManager.GetString("LightBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightCoral.
        /// </summary>
        internal static string LightCoral {
            get {
                return ResourceManager.GetString("LightCoral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Cyan.
        /// </summary>
        internal static string LightCyan {
            get {
                return ResourceManager.GetString("LightCyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Goldenrod Yellow.
        /// </summary>
        internal static string LightGoldenrodYellow {
            get {
                return ResourceManager.GetString("LightGoldenrodYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Gray.
        /// </summary>
        internal static string LightGray {
            get {
                return ResourceManager.GetString("LightGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Green.
        /// </summary>
        internal static string LightGreen {
            get {
                return ResourceManager.GetString("LightGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Pink.
        /// </summary>
        internal static string LightPink {
            get {
                return ResourceManager.GetString("LightPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Salmon.
        /// </summary>
        internal static string LightSalmon {
            get {
                return ResourceManager.GetString("LightSalmon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Sea Green.
        /// </summary>
        internal static string LightSeaGreen {
            get {
                return ResourceManager.GetString("LightSeaGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Sky Blue.
        /// </summary>
        internal static string LightSkyBlue {
            get {
                return ResourceManager.GetString("LightSkyBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Slate Gray.
        /// </summary>
        internal static string LightSlateGray {
            get {
                return ResourceManager.GetString("LightSlateGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Steel Blue.
        /// </summary>
        internal static string LightSteelBlue {
            get {
                return ResourceManager.GetString("LightSteelBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Yellow.
        /// </summary>
        internal static string LightYellow {
            get {
                return ResourceManager.GetString("LightYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lime.
        /// </summary>
        internal static string Lime {
            get {
                return ResourceManager.GetString("Lime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lime Green.
        /// </summary>
        internal static string LimeGreen {
            get {
                return ResourceManager.GetString("LimeGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linen.
        /// </summary>
        internal static string Linen {
            get {
                return ResourceManager.GetString("Linen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magenta.
        /// </summary>
        internal static string Magenta {
            get {
                return ResourceManager.GetString("Magenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maroon.
        /// </summary>
        internal static string Maroon {
            get {
                return ResourceManager.GetString("Maroon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauve.
        /// </summary>
        internal static string Mauve {
            get {
                return ResourceManager.GetString("Mauve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Aquamarine.
        /// </summary>
        internal static string MediumAquamarine {
            get {
                return ResourceManager.GetString("MediumAquamarine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Blue.
        /// </summary>
        internal static string MediumBlue {
            get {
                return ResourceManager.GetString("MediumBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Orchid.
        /// </summary>
        internal static string MediumOrchid {
            get {
                return ResourceManager.GetString("MediumOrchid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Purple.
        /// </summary>
        internal static string MediumPurple {
            get {
                return ResourceManager.GetString("MediumPurple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Sea Green.
        /// </summary>
        internal static string MediumSeaGreen {
            get {
                return ResourceManager.GetString("MediumSeaGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Slate Blue.
        /// </summary>
        internal static string MediumSlateBlue {
            get {
                return ResourceManager.GetString("MediumSlateBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Spring Green.
        /// </summary>
        internal static string MediumSpringGreen {
            get {
                return ResourceManager.GetString("MediumSpringGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Turquoise.
        /// </summary>
        internal static string MediumTurquoise {
            get {
                return ResourceManager.GetString("MediumTurquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Violet Red.
        /// </summary>
        internal static string MediumVioletRed {
            get {
                return ResourceManager.GetString("MediumVioletRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midnight Blue.
        /// </summary>
        internal static string MidnightBlue {
            get {
                return ResourceManager.GetString("MidnightBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mint Cream.
        /// </summary>
        internal static string MintCream {
            get {
                return ResourceManager.GetString("MintCream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misty Rose.
        /// </summary>
        internal static string MistyRose {
            get {
                return ResourceManager.GetString("MistyRose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moccasin.
        /// </summary>
        internal static string Moccasin {
            get {
                return ResourceManager.GetString("Moccasin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navajo White.
        /// </summary>
        internal static string NavajoWhite {
            get {
                return ResourceManager.GetString("NavajoWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navy.
        /// </summary>
        internal static string Navy {
            get {
                return ResourceManager.GetString("Navy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Lace.
        /// </summary>
        internal static string OldLace {
            get {
                return ResourceManager.GetString("OldLace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olive.
        /// </summary>
        internal static string Olive {
            get {
                return ResourceManager.GetString("Olive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olive Drab.
        /// </summary>
        internal static string OliveDrab {
            get {
                return ResourceManager.GetString("OliveDrab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        internal static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange Red.
        /// </summary>
        internal static string OrangeRed {
            get {
                return ResourceManager.GetString("OrangeRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orchid.
        /// </summary>
        internal static string Orchid {
            get {
                return ResourceManager.GetString("Orchid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pale Goldenrod.
        /// </summary>
        internal static string PaleGoldenrod {
            get {
                return ResourceManager.GetString("PaleGoldenrod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pale Green.
        /// </summary>
        internal static string PaleGreen {
            get {
                return ResourceManager.GetString("PaleGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pale Turquoise.
        /// </summary>
        internal static string PaleTurquoise {
            get {
                return ResourceManager.GetString("PaleTurquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pale Violet Red.
        /// </summary>
        internal static string PaleVioletRed {
            get {
                return ResourceManager.GetString("PaleVioletRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Papaya Whip.
        /// </summary>
        internal static string PapayaWhip {
            get {
                return ResourceManager.GetString("PapayaWhip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peach Puff.
        /// </summary>
        internal static string PeachPuff {
            get {
                return ResourceManager.GetString("PeachPuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peru.
        /// </summary>
        internal static string Peru {
            get {
                return ResourceManager.GetString("Peru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink.
        /// </summary>
        internal static string Pink {
            get {
                return ResourceManager.GetString("Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plum.
        /// </summary>
        internal static string Plum {
            get {
                return ResourceManager.GetString("Plum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powder Blue.
        /// </summary>
        internal static string PowderBlue {
            get {
                return ResourceManager.GetString("PowderBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        internal static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rosy Brown.
        /// </summary>
        internal static string RosyBrown {
            get {
                return ResourceManager.GetString("RosyBrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Royal Blue.
        /// </summary>
        internal static string RoyalBlue {
            get {
                return ResourceManager.GetString("RoyalBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saddle Brown.
        /// </summary>
        internal static string SaddleBrown {
            get {
                return ResourceManager.GetString("SaddleBrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salmon.
        /// </summary>
        internal static string Salmon {
            get {
                return ResourceManager.GetString("Salmon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandy Brown.
        /// </summary>
        internal static string SandyBrown {
            get {
                return ResourceManager.GetString("SandyBrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sea Green.
        /// </summary>
        internal static string SeaGreen {
            get {
                return ResourceManager.GetString("SeaGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sea Shell.
        /// </summary>
        internal static string SeaShell {
            get {
                return ResourceManager.GetString("SeaShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sienna.
        /// </summary>
        internal static string Sienna {
            get {
                return ResourceManager.GetString("Sienna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver.
        /// </summary>
        internal static string Silver {
            get {
                return ResourceManager.GetString("Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sky Blue.
        /// </summary>
        internal static string SkyBlue {
            get {
                return ResourceManager.GetString("SkyBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slate Blue.
        /// </summary>
        internal static string SlateBlue {
            get {
                return ResourceManager.GetString("SlateBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slate Gray.
        /// </summary>
        internal static string SlateGray {
            get {
                return ResourceManager.GetString("SlateGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow.
        /// </summary>
        internal static string Snow {
            get {
                return ResourceManager.GetString("Snow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spring Green.
        /// </summary>
        internal static string SpringGreen {
            get {
                return ResourceManager.GetString("SpringGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steel.
        /// </summary>
        internal static string Steel {
            get {
                return ResourceManager.GetString("Steel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steel Blue.
        /// </summary>
        internal static string SteelBlue {
            get {
                return ResourceManager.GetString("SteelBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tan.
        /// </summary>
        internal static string Tan {
            get {
                return ResourceManager.GetString("Tan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taupe.
        /// </summary>
        internal static string Taupe {
            get {
                return ResourceManager.GetString("Taupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teal.
        /// </summary>
        internal static string Teal {
            get {
                return ResourceManager.GetString("Teal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thistle.
        /// </summary>
        internal static string Thistle {
            get {
                return ResourceManager.GetString("Thistle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomato.
        /// </summary>
        internal static string Tomato {
            get {
                return ResourceManager.GetString("Tomato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparent.
        /// </summary>
        internal static string Transparent {
            get {
                return ResourceManager.GetString("Transparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turquoise.
        /// </summary>
        internal static string Turquoise {
            get {
                return ResourceManager.GetString("Turquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violet.
        /// </summary>
        internal static string Violet {
            get {
                return ResourceManager.GetString("Violet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wheat.
        /// </summary>
        internal static string Wheat {
            get {
                return ResourceManager.GetString("Wheat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        internal static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White Smoke.
        /// </summary>
        internal static string WhiteSmoke {
            get {
                return ResourceManager.GetString("WhiteSmoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        internal static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow Green.
        /// </summary>
        internal static string YellowGreen {
            get {
                return ResourceManager.GetString("YellowGreen", resourceCulture);
            }
        }
    }
}
